require "rake/testtask"
SEEDS = {
  long: <<~SEED.strip,
    ...............................
    ...............................
    ...OOO...................OOO...
    ...OOO...................OOO...
    ...OOO...................OOO...
    ..............OOO..............
    ..............OOO..............
    ..............OOO..............
    ...OOO...................OOO...
    ...OOO...................OOO...
    ...OOO...................OOO...
    ...............................
    ...............................
  SEED
  blinker: <<~SEED.strip,
    .......
    .......
    ..OOO..
    .......
    .......
  SEED
  glider: <<~SEED.strip,
    ..................
    ....O.............
    .....O............
    ...OOO............
    ..................
    ..................
    ..................
    ..................
    ..................
  SEED
  spaceship: <<~SEED.strip,
    .................................
    .................................
    .................................
    .................................
    .................................
    .................................
    .................................
    ............O.......O............
    ......OO.O.O.OO...OO.O.O.OO......
    ...OOO.O.OOO.........OOO.O.OOO...
    ...O...O.O.....O.O.....O.O...O...
    .......OO......O.O......OO.......
    ....OO.........O.O.........OO....
    ....OO.OO...............OO.OO....
    ........O...............O........
  SEED
  question: <<~SEED.strip
    ...............................
    ...............................
    ............OOOOO..............
    ...........OOOOOOO.............
    ..........OO.....OO............
    .................OO............
    ................OO.............
    ..............OO...............
    ..............OO...............
    ...............................
    ..............OO...............
    ..............OO...............
    ...............................
    ...............................
  SEED
}.freeze

DELAYS = {
  blinker: 0.5,
  glider: 0.2,
  question: 1
}

Rake::TestTask.new do |t|
  t.test_files = FileList["test/**/*_test.rb"]
  t.libs << "test"
  t.warning = false
end
desc "Run Tests"

desc "Run with a sample seed"
task :run do
  $LOAD_PATH << File.expand_path("./lib", File.dirname(__FILE__))
  seed = SEEDS[ENV['SEED']&.to_sym]
  delay = DELAYS[ENV['SEED']&.to_sym] || 0.1
  unless seed
    puts "Please run with a SEED variable set to one of:\n#{SEEDS.keys.join(", ")}"
    exit
  end
  require "cellular_automata"

  grid = CellularAutomata::Grid.from_s(seed)
  game = CellularAutomata::Game.new(rules: CellularAutomata::Rules::Life, grid: grid)

  generation = 0
  while true
    puts "\e[H\e[2J" # clear screen
    puts "Generation: #{generation += 1}"
    puts game.grid.to_s 
    game.next
    sleep delay
  end
end

task default: :test
